### ISSUE TITLE
Credentials Context v2?

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/bedrock-credentials-context#7]
v2 of the credentials-context module was release 2019-09-20, but for some reason was never updated here.

https://github.com/digitalbazaar/credentials-context/blob/main/CHANGELOG.md
https://github.com/digitalbazaar/credentials-context/pull/4

It's unclear to me why this was a breaking release.

@dlongley can you recommend the path forward for this?

**Comment by dlongley** [comment]
My understanding is that the hash for the context will be different from what is in the specification with this change -- something that I don't think anyone was depending on with this package, but could have been.  The changelog removed the relevant part I was commenting on in this commit that changed it to a major change:

https://github.com/digitalbazaar/credentials-context/pull/4/commits/9a0d3889b264e4c345caf7ff840240166886833c

Where the `.jsonld` file is now generated instead of using a static copy with a hash that matches the VCDM v1.1 spec.

I think it never got released because Dmitri merged the PR ... instead of a release manager doing it and so no one was there to complete the process. The resolution should be to add that the hash for the context file will be different from what's in the VCDM v1.1 spec, but the functional contents are the same -- and that's what's breaking. Then it can be released.

**Comment by davidlehn** [comment]
Done in 5.0.0.
